version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: biolens-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: biolens
      POSTGRES_PASSWORD: biolens123
      POSTGRES_DB: biolens_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
